# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-16 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0011_auto_20181112_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='sa_api_v2.DataSet')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sa_api_v2.Label')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ms_api_label',
            },
        ),
        migrations.CreateModel(
            name='LabelClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelclosure_parents', to='sa_api_v2.Label')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelclosure_children', to='sa_api_v2.Label')),
            ],
            options={
                'db_table': 'ms_api_labelclosure',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('updated_datetime', models.DateTimeField(auto_now=True, db_index=True)),
                ('note', models.TextField(blank=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='sa_api_v2.Label')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sa_api_v2.Place')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_datetime'],
                'db_table': 'ms_api_tag',
            },
        ),
        migrations.AlterUniqueTogether(
            name='labelclosure',
            unique_together=set([('parent', 'child')]),
        ),
    ]
