# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-01 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0012_auto_20190123_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasnapshotrequest',
            old_name='include_private',
            new_name='include_private_fields',
        ),
        migrations.AddField(
            model_name='datasnapshotrequest',
            name='include_private_places',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='private',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
